# Generated by Django 6.0.3 on 2026-03-12 14:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(choices=[('45T', '45 tours'), ('33T', '33 tours'), ('CD', 'cd')], default='45T', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Artiste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('label_apartenance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='collection.label')),
            ],
        ),
        migrations.CreateModel(
            name='Piste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('duree', models.DecimalField(decimal_places=2, max_digits=4)),
                ('compositeur', models.CharField(blank=True, max_length=255, null=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.artiste')),
            ],
        ),
        migrations.CreateModel(
            name='Disc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_alblum', models.CharField(max_length=255)),
                ('bio', models.TextField(blank=True, null=True)),
                ('date_published', models.DateField(verbose_name='date de publication')),
                ('date_acquisition', models.DateField(default=django.utils.timezone.now, verbose_name="date d'achat")),
                ('prix', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('auteurs', models.ManyToManyField(to='collection.artiste')),
                ('pistes', models.ManyToManyField(to='collection.piste')),
            ],
        ),
    ]
