# Generated by Django 6.0.3 on 2026-03-12 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disc',
            name='jacket',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
