# Generated by Django 6.0.3 on 2026-03-13 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_disc_jacket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disc',
            old_name='nom_alblum',
            new_name='nom_album',
        ),
    ]
