# Generated by Django 6.0.3 on 2026-03-13 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_rename_nom_alblum_disc_nom_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='disc',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='collection.categorie'),
        ),
    ]
