# Generated by Django 6.0.3 on 2026-03-13 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0004_disc_categorie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disc',
            name='bio',
        ),
        migrations.AddField(
            model_name='artiste',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
