# Generated by Django 6.0.3 on 2026-03-13 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0005_remove_disc_bio_artiste_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='disc',
            name='jacket',
            field=models.ImageField(blank=True, null=True, upload_to='collection/images/'),
        ),
        migrations.AddField(
            model_name='disc',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='collection.genre'),
        ),
    ]
