# Generated by Django 6.0.3 on 2026-03-13 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0006_genre_alter_disc_jacket_disc_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piste',
            name='duree',
            field=models.CharField(max_length=10),
        ),
    ]
